kafka:
  connect:
    bootstrap_servers: "host:port"
    security_protocol: SSL
    ssl_cafile: config/ca.pem
    ssl_certfile: config/service.cert
    ssl_keyfile: config/service.key
  topic: "my_favorite_topic"
postgresql:
  uri: "postgres://login:password@host:port/database"
checks:
  - url: http://petersmol.ru/
    expected_code: 302
  - url: https://aiven.io/